[build]
  publish = "/public"
  functions = './functions'

[dev]
  command = "python -m http.server --directory public"
  port = 3000
  targetPort = 8000
  autoLaunch = true
  publish = "/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
